config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'
  get 'conversations/index'
  devise_for :users
  root "products#home"
  get "/restricted", to: "products#restricted", as: "restricted"
  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"
  resources :products
  resources :profiles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :picture
  


end

app/controllers/profiles_controller.rb
require_relative 'products_controller'  

class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]
  before_action :all_profiles, only: %i[ index ]
  
  def index
    # @profile = Profile.find(1)
    @profile = Profile.find_by(user: current_user)

    if !@profile
      redirect_to new_profile_url
    end
    puts "@profile is here:"
    p @profile
  end

  def show
    
  end
  def new
    @profile = Profile.new
  end

  def edit
  end

  def create
    # @profile = current_user.profile.create(profile_params)
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def restricted
  end

  def destroy
    @profile.destroy
  
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def all_profiles
      @profiles = Profile.all
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:fname, :lname, :location, :activity, :seller, :buyer, :selfintro, :picture)
    end

    def get_products
      @product_list = Product.where(user_id: current_user.id, sold: false)
    end

end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile) do |form| %>

  <div class="field">
    <%= form.label :fname %>
    <%= form.text_field :fname %>
  </div>
  
  <div class="field">
    <%= form.label :lname %>
    <%= form.text_field :lname %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>


  <div class="field">
    <%= form.label :activity %>
    <%= form.number_field :quantity, min: 1, max: 10000 %>
  </div>

  <div class="field">
    <%= form.label :seller %>
    <%= form.check_box :seller %>
  </div>

  <div class="field">
    <%= form.label :buyer %>
    <%= form.check_box :buyer %>
  </div>

  <div class="field">
    <%= form.label :selfintro %>
    <%= form.text_area :brand %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, accept: 'image/png, image/jpg, image/jpeg'%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profile</h1>

<div class="profile">

<% if user_signed_in? %> 
  <%# <%= link_to image_tag("profile.png", class: "profile-photo"), "/"%>  
  <h2><%="#{current_user.username}'s Profile" %></h2>

<div>
  <p>
    <strong>First Name:</strong>
    <%= @profile.fname %>
  </p>

  <p>
    <strong>Last Name:</strong>
    <%= @profile.lname %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= @profile.location %>
  </p>

  <p>
    <strong>Activity No.:</strong>
    <%= @profile.activity %>
  </p>

  <p>
    <strong>Seller:</strong>
    <%= @profile.seller %>
  </p>

  <p>
    <strong>Buyer:</strong>
    <%= @profile.buyer %>
  </p>

  <p>
    <strong>Self Intro:</strong>
    <%= @profile.selfintro %>
  </p>

  <p>
    <strong>Picture:</strong>
    <% image_tag @profile.picture %>
</div>

<% if user_signed_in? && current_user.id == @profile.user_id %>
        <td><%= link_to 'Edit', edit_profile_path(@profile) %></td>
        <td><%= link_to 'Destroy', @profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
        <% end %>

<% end %>

</div>

app/views/profiles/new.html.erb
<h1>Add New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>