config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'
  get 'conversations/index'
  devise_for :users
  root "products#home"
  get "/restricted", to: "products#restricted", as: "restricted"
  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"
  resources :products
  resources :profiles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end
end

app/models/conversation.rb
class Conversation < ApplicationRecord
    belongs_to :sender, class_name: "User", foreign_key: "sender_id"
    belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
    has_many :messages, dependent: :destroy
  
    validates_uniqueness_of :sender_id, scope: :receiver_id
  
    scope :between, -> (sender_id, receiver_id) do
      where("(conversations.sender_id = ? AND conversations.receiver_id = ?) OR (conversations.receiver_id = ? AND conversations.sender_id = ?)", sender_id, receiver_id, sender_id, receiver_id)
    end
  
    def recipient(current_user)
      self.sender_id == current_user.id ? self.receiver : self.sender
    end

    def unread_message_count(current_user)
        self.messages.where("user_id != ? AND read = ?", current_user.id, false).count
    end
  
  end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.where.not(id: current_user.id)
    @conversations = Conversation.where("sender_id = ? OR receiver_id = ?", current_user.id, current_user.id)
    p "here:"
    p @conversations
  end

  def create
    if Conversation.between(params[:sender_id], params[:receiver_id]).present?
      @conversation = Conversation.between(params[:sender_id], params[:receiver_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end

    redirect_to conversation_messages_path(@conversation)
  end

    private
    def conversation_params
      params.permit(:sender_id, :receiver_id)
    end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/index.html.erb
<h1>Inbox</h1>
<div>
  From:
  <% @conversations.each do |conversation| %>
      <%= link_to conversation.recipient(current_user).username, conversation_messages_path(conversation) %>
      <% if !conversation.unread_message_count(current_user).zero? %>
        (<%= conversation.unread_message_count(current_user) %>)
      <% end %>
  <% end %>
</div>


<%# <h2>Users</h2> %>
<%# <ul> %>
  <%# <% @users.each do |user| %> 
    <%# <li>
    <%= link_to user.username, conversations_path(sender_id: current_user.id, receiver_id: user.id), method: :post %>
    <%#</li> 
  <%# <% end %> 
<%# </ul> %>